# Netflix Content Analytics & Recommendation
## Business Context

Netflix operates a large and diverse content catalog consisting of movies and TV shows across different genres, countries, release periods, and content types. As the catalog expands, effectively understanding and utilizing this content data becomes increasingly important.

Two areas of opportunity are particularly relevant: improving how users discover relevant content and generating data-driven insights into the composition and evolution of the content catalog.

This analysis uses Netflix catalog data to examine content patterns, develop a content-based recommendation approach, identify historical trends, forecast future content growth, and generate insights that could support content discovery and strategic decision-making.

## Business Objective

The objective of this analysis is to transform Netflix catalog data into actionable insights that can help answer questions such as:

What does Netflix's content catalog look like across different markets, genres, and time periods?
What patterns and trends can be identified in the growth and composition of the catalog?
How can available content information be used to identify titles that are similar to one another?
What future content trends can be anticipated from historical patterns?
What predictive insights can be derived from the available content attributes?

The analysis will ultimately connect these findings to potential opportunities to improve content discovery and support data-driven decisions regarding Netflix's content portfolio.

## Data Understanding

The project uses a Netflix titles dataset containing metadata for movies and TV shows available on the platform. The dataset provides information about the content itself, its production details, catalog addition date, release year, rating, duration, and content categories.

### Dataset Overview

The dataset initially contained **8,790 records and 10 variables**. Each row represents a Netflix title, while the columns describe different attributes of that title.

| Attribute                    | Description                           |
| ---------------------------- | ------------------------------------- |
| **Rows**                     | 8,790                                 |
| **Columns**                  | 10                                    |
| **Content types**            | Movies and TV Shows                   |
| **Time-related information** | Release year and date added           |
| **Categorical information**  | Type, rating, country, and categories |
| **Content information**      | Title, director, and duration         |

### Variables and Data Types

| Variable       | Data Type | Description                                                     |
| -------------- | --------- | --------------------------------------------------------------- |
| `show_id`      | Object    | Unique identifier for each title                                |
| `type`         | Object    | Indicates whether the title is a Movie or TV Show               |
| `title`        | Object    | Name of the title                                               |
| `director`     | Object    | Director associated with the title                              |
| `country`      | Object    | Country or countries associated with the title                  |
| `date_added`   | Datetime  | Date the title was added to the Netflix catalog                 |
| `release_year` | Integer   | Year the title was released                                     |
| `rating`       | Object    | Content rating assigned to the title                            |
| `duration`     | Object    | Runtime in minutes for movies or number of seasons for TV shows |
| `listed_in`    | Object    | Categories or genres associated with the title                  |

### Understanding the Data Structure

The dataset combines **categorical, textual, numerical, and date-related information**. Some fields, such as `country` and `listed_in`, contain multiple values within a single record, while `duration` uses different units depending on the content type. These characteristics are important when determining how the data should be cleaned, transformed, and later represented for analysis and machine learning.

The dataset therefore provides several dimensions for analysis, including content distribution, production geography, genre patterns, release trends, content characteristics, and relationships between different title attributes. This understanding informed the subsequent data-quality assessmens addressed throughout the analysis.

## Data Preparation

Reliable analysis depends on reliable data. Before investigating trends or developing predictive models, the Netflix dataset will be assessed and prepared to ensure that the information used throughout the analysis is sufficiently complete, consistent, and suitable for the intended analytical applications.

### The data preparation process will focus on:

Understanding the structure and characteristics of the available data
Identifying missing, duplicated, inconsistent, or potentially invalid records
Standardizing variables and categorical values where necessary
Creating features that provide additional analytical value
Validating the resulting dataset before downstream analysis

The objective is not simply to clean the dataset, but to establish a reliable analytical foundation for the business questions addressed throughout the analysis.

### 1. Data Loading & Initial Inspection

Before assessing and improving data quality, the available Netflix content data must first be examined to understand its structure, coverage, and characteristics.

This initial inspection establishes a baseline for the raw dataset and helps identify potential issues that may affect subsequent analysis and modeling.

The assessment will focus on:

* Dataset dimensions and structure
* Available variables and their data types
* Missing values
* Duplicate records
* Unique and categorical values
* Basic descriptive statistics

The findings from this stage will guide the subsequent data cleaning and feature engineering decisions.

In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [2]:
# Loading our dataset
netflix_df = pd.read_csv("Dataset.csv")

In [3]:
netflix_df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [4]:
# Convert valid date strings into pandas datetime values
netflix_df["date_added"] = pd.to_datetime(netflix_df["date_added"])

In [5]:
# Confirm the updated data type and check for missing dates
netflix_df["date_added"].dtype, netflix_df["date_added"].isna().sum()

(dtype('<M8[ns]'), 0)

In [6]:
# analyzing the number of records and columns in our dataset
netflix_df.shape

(8790, 10)

In [7]:
# checking the data types contained in different columns of our dataset
netflix_df.dtypes

show_id                 object
type                    object
title                   object
director                object
country                 object
date_added      datetime64[ns]
release_year             int64
rating                  object
duration                object
listed_in               object
dtype: object

In [8]:
netflix_df.info

<bound method DataFrame.info of      show_id     type                             title         director  \
0         s1    Movie              Dick Johnson Is Dead  Kirsten Johnson
1         s3  TV Show                         Ganglands  Julien Leclercq
2         s6  TV Show                     Midnight Mass    Mike Flanagan
3        s14    Movie  Confessions of an Invisible Girl    Bruno Garotti
4         s8    Movie                           Sankofa     Haile Gerima
...      ...      ...                               ...              ...
8785   s8797  TV Show                        Yunus Emre        Not Given
8786   s8798  TV Show                         Zak Storm        Not Given
8787   s8801  TV Show                Zindagi Gulzar Hai        Not Given
8788   s8784  TV Show                              Yoko        Not Given
8789   s8786  TV Show                               YOM        Not Given

            country date_added  release_year rating   duration  \
0     United States 2021-09-25          2020  PG-13     90 min
1            France 2021-09-24          2021  TV-MA   1 Season
2     United States 2021-09-24          2021  TV-MA   1 Season
3            Brazil 2021-09-22          2021  TV-PG     91 min
4     United States 2021-09-24          1993  TV-MA    125 min
...             ...        ...           ...    ...        ...
8785         Turkey 2017-01-17          2016  TV-PG  2 Seasons
8786  United States 2018-09-13          2016  TV-Y7  3 Seasons
8787       Pakistan 2016-12-15          2012  TV-PG   1 Season
8788       Pakistan 2018-06-23          2016   TV-Y   1 Season
8789       Pakistan 2018-06-07          2016  TV-Y7   1 Season

                                              listed_in
0                                         Documentaries
1     Crime TV Shows, International TV Shows, TV Act...
2                    TV Dramas, TV Horror, TV Mysteries
3                    Children & Family Movies, Comedies
4      Dramas, Independent Movies, International Movies
...                                                 ...
8785                  International TV Shows, TV Dramas
8786                                           Kids' TV
8787  International TV Shows, Romantic TV Shows, TV ...
8788                                           Kids' TV
8789                                           Kids' TV

[8790 rows x 10 columns]>

In [9]:
netflix_df. describe(include = "all")

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
count,8790,8790,8790,8790,8790,8790,8790.000000,8790,8790,8790
unique,8790,2,8787,4528,86,NaN,NaN,14,220,513
top,s1,Movie,9-Feb,Not Given,United States,NaN,NaN,TV-MA,1 Season,"Dramas, International Movies"
freq,1,6126,2,2588,3240,NaN,NaN,3205,1791,362
mean,NaN,NaN,NaN,NaN,NaN,2019-05-17 21:44:01.638225408,2014.183163,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,2008-01-01 00:00:00,1925.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,2018-04-06 00:00:00,2013.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,2019-07-03 00:00:00,2017.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,2020-08-19 18:00:00,2019.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,2021-09-25 00:00:00,2021.000000,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,8.825466,NaN,NaN,NaN

In [10]:
# investigating nulls
netflix_df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [11]:
netflix_df.duplicated().sum()

0

#### Observation
After some investigation and data quality checks, I just found out that this dataset 8790 rows and 10 columns. It does not have any record of duplicated records and no nulls as well.

### 2. Data quality checks
I will be checking the formatting and consistency in naming and and also have the date_added column formated to datetime.

In [12]:
# Compare unique show IDs with the total number of records
netflix_df["show_id"].nunique(), netflix_df.shape[0]

(8790, 8790)

In [13]:
# Count each content type, including missing values
netflix_df["type"].value_counts(dropna=False)

type
Movie      6126
TV Show    2664
Name: count, dtype: int64

In [14]:
# Count each rating category, including missing values
netflix_df["rating"].value_counts(dropna=False)

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [15]:
# Display all unique rating values
netflix_df["rating"].unique()

array(['PG-13', 'TV-MA', 'TV-PG', 'TV-14', 'TV-Y7', 'TV-Y', 'PG', 'TV-G',
       'R', 'G', 'NC-17', 'NR', 'TV-Y7-FV', 'UR'], dtype=object)

**Finding:** The rating field contains 14 distinct rating categories with varying frequencies. The values appear consistently formatted, with no immediate evidence of capitalization or whitespace inconsistencies. Both TV and film rating systems are represented, which is consistent with the dataset containing multiple content types.

In [16]:
# Inspect the first few date values and their current representation
netflix_df["date_added"].head(10)

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-22
4   2021-09-24
5   2021-09-24
6   2021-09-24
7   2021-05-01
8   2021-09-23
9   2021-05-01
Name: date_added, dtype: datetime64[ns]

In [17]:
# Sample non-missing dates to check formatting consistency
netflix_df["date_added"].dropna().sample(20, random_state=42)

3942   2017-05-01
8360   2017-05-22
221    2021-01-01
4883   2019-06-06
2210   2020-03-31
3527   2018-05-04
1075   2021-04-08
4469   2018-03-01
8525   2018-02-01
2926   2019-03-29
1057   2021-04-15
7557   2019-10-01
6706   2021-06-25
7000   2020-11-11
828    2021-06-11
1832   2020-07-18
2276   2020-03-01
2893   2019-04-15
1084   2021-04-03
6802   2021-04-14
Name: date_added, dtype: datetime64[ns]

In [18]:
# Test whether all non-missing date values can be interpreted as valid dates
parsed_dates = pd.to_datetime(netflix_df["date_added"], errors="coerce")

parsed_dates.isna().sum()

0

### Investigating Director Name Variations

The initial consistency check identified director names that differ only in capitalization. These variations can cause the same director to be counted as separate individuals, so the affected records will be examined before standardizing the names.

In [19]:
# Display the most frequent director names
netflix_df["director"].value_counts(dropna=False).head(20)

director
Not Given                       2588
Rajiv Chilaka                     20
Alastair Fothergill               18
Raúl Campos, Jan Suter            18
Suhas Kadav                       16
Marcus Raboy                      16
Jay Karas                         14
Cathy Garcia-Molina               13
Martin Scorsese                   12
Youssef Chahine                   12
Jay Chapman                       12
Steven Spielberg                  11
Mark Thornton, Todd Kauffman      10
Don Michael Paul                  10
David Dhawan                       9
Ryan Polito                        8
Johnnie To                         8
Lance Bangs                        8
Troy Miller                        8
Robert Rodriguez                   8
Name: count, dtype: int64

In [20]:
netflix_df["director"].value_counts().unique()

array([2588,   20,   18,   16,   14,   13,   12,   11,   10,    9,    8,
          7,    6,    5,    4,    3,    2,    1], dtype=int64)

In [21]:
# Identify director names with leading or trailing whitespace
director_whitespace = (
    netflix_df["director"].dropna().astype(str).str.strip()
    != netflix_df["director"].dropna().astype(str)
)

director_whitespace.sum()

0

In [22]:
# Find names that may differ only by capitalization
director_case_check = (
    netflix_df["director"]
    .dropna()
    .groupby(netflix_df["director"].dropna().str.lower())
    .filter(lambda x: x.nunique() > 1)
)

director_case_check.unique()

array(['Kevin Macdonald', 'Fernando Frías de la Parra', 'Kevin MacDonald',
       'Fernando Frías De La Parra'], dtype=object)

In [23]:
# Display records containing the identified director name variations
director_variations = netflix_df[
    netflix_df["director"].isin([
        "Kevin Macdonald",
        "Kevin MacDonald",
        "Fernando Frías de la Parra",
        "Fernando Frías De La Parra"
    ])
]

director_variations[["title", "director"]]

                                     title                    director
978                          State of Play             Kevin Macdonald
2001                    I'm No Longer Here  Fernando Frías de la Parra
3012                             Black Sea             Kevin MacDonald
4120  Sky Ladder: The Art of Cai Guo-Qiang             Kevin MacDonald
5757                                Rezeta  Fernando Frías De La Parra

In [24]:
# Count each variation to determine the number of affected records
director_variations["director"].value_counts()

director
Kevin MacDonald               2
Kevin Macdonald               1
Fernando Frías de la Parra    1
Fernando Frías De La Parra    1
Name: count, dtype: int64

In [25]:
# Standardize confirmed capitalization variations in director names
director_name_map = {
    "Kevin Macdonald": "Kevin MacDonald",
    "Fernando Frías de la Parra": "Fernando Frías De La Parra"
}

netflix_df["director"] = netflix_df["director"].replace(director_name_map)

In [26]:
# Check that the inconsistent director names have been standardized
netflix_df[
    netflix_df["director"].isin([
        "Kevin MacDonald",
        "Fernando Frías De La Parra"
    ])
][["title", "director"]]

                                     title                    director
978                          State of Play             Kevin MacDonald
2001                    I'm No Longer Here  Fernando Frías De La Parra
3012                             Black Sea             Kevin MacDonald
4120  Sky Ladder: The Art of Cai Guo-Qiang             Kevin MacDonald
5757                                Rezeta  Fernando Frías De La Parra

In [27]:
# Identify columns containing the "Not Given" placeholder
not_given_counts = (netflix_df == "Not Given").sum()

not_given_counts[not_given_counts > 0]

director    2588
country      287
dtype: int64

In [28]:
# Replace the source placeholder with a consistent missing-value label
netflix_df[["director", "country"]] = netflix_df[["director", "country"]].replace("Not Given", "N/A")

In [29]:
# Confirm that "Not Given" no longer appears in these columns
(netflix_df[["director", "country"]] == "Not Given").sum()

director    0
country     0
dtype: int64

In [30]:
# Identify director names that still have capitalization variations
director_case_variations = (
    netflix_df["director"]
    .dropna()
    .groupby(netflix_df["director"].dropna().str.lower())
    .filter(lambda x: x.nunique() > 1)
)

director_case_variations.unique()

array([], dtype=object)

### Checking Country Naming Consistency

The `country` field may contain one or multiple countries for a title. The values will be examined for naming and formatting inconsistencies, including capitalization, spacing, and variations in how countries are represented.

In [31]:
# Display the most frequent country entries
netflix_df["country"].value_counts(dropna=False).head(30)

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
N/A                287
Canada             271
Japan              259
South Korea        214
France             213
Spain              182
Mexico             138
Egypt              123
Australia          114
Turkey             112
Nigeria            105
Germany            104
China              100
Brazil              88
Taiwan              86
Indonesia           86
Philippines         83
Hong Kong           79
Argentina           76
Italy               66
Thailand            66
Colombia            42
South Africa        42
Denmark             30
Poland              30
Netherlands         28
Name: count, dtype: int64

In [32]:
# Split multi-country entries into individual country names for consistency checking
country_names = (
    netflix_df["country"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

country_names.value_counts().head(40)

country
United States           3240
India                   1057
United Kingdom           638
Pakistan                 421
N/A                      287
Canada                   271
Japan                    259
South Korea              214
France                   213
Spain                    182
Mexico                   138
Egypt                    123
Australia                114
Turkey                   112
Nigeria                  105
Germany                  104
China                    100
Brazil                    88
Taiwan                    86
Indonesia                 86
Philippines               83
Hong Kong                 79
Argentina                 76
Italy                     66
Thailand                  66
Colombia                  42
South Africa              42
Denmark                   30
Poland                    30
Netherlands               28
Ireland                   28
Singapore                 28
Lebanon                   24
Malaysia                  23
Israel                    22
Chile                     22
Norway                    21
United Arab Emirates      21
Russia                    19
Sweden                    19
Name: count, dtype: int64

In [33]:
# Identify country names that appear with different capitalization
country_case_variations = (
    country_names.groupby(country_names.str.lower())
    .filter(lambda x: x.nunique() > 1)
)

country_case_variations.unique()

array([], dtype=object)

In [34]:
# Extract individual country names from multi-country entries
country_names = (
    netflix_df["country"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

# Display all unique country names alphabetically
sorted(country_names.unique())

['Argentina',
 'Australia',
 'Austria',
 'Bangladesh',
 'Belarus',
 'Belgium',
 'Brazil',
 'Bulgaria',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Chile',
 'China',
 'Colombia',
 'Croatia',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Egypt',
 'Finland',
 'France',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Guatemala',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kenya',
 'Kuwait',
 'Lebanon',
 'Luxembourg',
 'Malaysia',
 'Mauritius',
 'Mexico',
 'Mozambique',
 'N/A',
 'Namibia',
 'Netherlands',
 'New Zealand',
 'Nigeria',
 'Norway',
 'Pakistan',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Romania',
 'Russia',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Singapore',
 'Slovenia',
 'Somalia',
 'South Africa',
 'South Korea',
 'Soviet Union',
 'Spain',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Thailand',
 'Turkey',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Venezuela',
 'Vietnam',
 'West Germany',
 'Zimbabwe']

In [35]:
# Check for individual country names with leading or trailing whitespace
country_whitespace = country_names[
    country_names != country_names.str.strip()
]

country_whitespace.unique()

array([], dtype=object)

#### Country Formatting Validation
**Finding:** The `country` field was checked for capitalization differences, alternative country names or aliases, and leading/trailing whitespace. No formatting or naming inconsistencies were identified. Multi-country entries were retained as valid values, while `Not Given` was identified as a missing-information placeholder.

**Action:** No formatting changes were required for the `country` field. `Not Given` will be addressed during the missing-value assessment.

### Checking listed_in Naming Consistency

The listed_in field contains one or more categories for each title. The category names will be reviewed for inconsistent capitalization, spacing, and duplicate representations that could affect category-level analysis.

In [36]:
# Display the most frequent category combinations
netflix_df["listed_in"].value_counts().head(30)

listed_in
Dramas, International Movies                              362
Documentaries                                             359
Stand-Up Comedy                                           334
Comedies, Dramas, International Movies                    274
Dramas, Independent Movies, International Movies          252
Kids' TV                                                  219
Children & Family Movies                                  215
Children & Family Movies, Comedies                        201
Documentaries, International Movies                       186
Dramas, International Movies, Romantic Movies             180
Comedies, International Movies                            176
Comedies, International Movies, Romantic Movies           152
Dramas                                                    137
Dramas, International Movies, Thrillers                   134
Action & Adventure, Dramas, International Movies          132
Action & Adventure                                        128
International TV Shows, TV Dramas                         121
Comedies, Dramas, Independent Movies                      116
Crime TV Shows, International TV Shows, TV Dramas         110
Comedies                                                  110
Action & Adventure, International Movies                  101
Dramas, Independent Movies                                100
Kids' TV, TV Comedies                                      97
Reality TV                                                 95
International TV Shows, Romantic TV Shows, TV Comedies     94
International TV Shows, Romantic TV Shows, TV Dramas       90
Anime Series, International TV Shows                       87
Docuseries                                                 84
Dramas, Thrillers                                          82
Documentaries, Music & Musicals                            82
Name: count, dtype: int64

In [37]:
# Split multi-category entries into individual category names
listed_in_names = (
    netflix_df["listed_in"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

# Display individual categories by frequency
listed_in_names.value_counts().head(30)

listed_in
International Movies         2752
Dramas                       2426
Comedies                     1674
International TV Shows       1349
Documentaries                 869
Action & Adventure            859
TV Dramas                     762
Independent Movies            756
Children & Family Movies      641
Romantic Movies               616
Thrillers                     577
TV Comedies                   573
Crime TV Shows                469
Kids' TV                      448
Docuseries                    394
Music & Musicals              375
Romantic TV Shows             370
Horror Movies                 357
Stand-Up Comedy               343
Reality TV                    255
British TV Shows              252
Sci-Fi & Fantasy              243
Sports Movies                 219
Anime Series                  174
Spanish-Language TV Shows     173
TV Action & Adventure         167
Korean TV Shows               151
Classic Movies                116
LGBTQ Movies                  102
TV Mysteries                   98
Name: count, dtype: int64

In [38]:
# Identify categories that differ only by capitalization
listed_in_case_variations = (
    listed_in_names.groupby(listed_in_names.str.lower())
    .filter(lambda x: x.nunique() > 1)
)

listed_in_case_variations.unique()

array([], dtype=object)

In [39]:
# Check for leading or trailing whitespace in category names
listed_in_whitespace = listed_in_names[
    listed_in_names != listed_in_names.str.strip()
]

listed_in_whitespace.unique()

array([], dtype=object)

#### Listed In Consistency Finding
**Finding**: The listed_in field was reviewed for capitalization inconsistencies and leading or trailing whitespace after separating multi-category entries. No formatting inconsistencies were identified. The different category names represent distinct content classifications rather than duplicate naming variations.

**Action**: No formatting changes were required for the listed_in field. The multi-category structure will be retained for subsequent analysis and feature engineering.

### Checking Duration Consistency

The duration field contains information about the length of both movies and TV shows. Because these content types use different units, the field will be examined for consistent formatting, valid duration values, and unexpected entries before transformation.

In [40]:
# Display the most common duration values
netflix_df["duration"].value_counts(dropna=False).head(30)

duration
1 Season     1791
2 Seasons     421
3 Seasons     198
90 min        152
97 min        146
93 min        146
94 min        146
91 min        144
95 min        137
96 min        130
92 min        129
102 min       122
98 min        120
99 min        118
101 min       116
88 min        116
103 min       114
106 min       111
100 min       108
89 min        106
104 min       104
86 min        103
87 min        101
105 min       101
107 min        98
110 min        97
4 Seasons      94
108 min        87
116 min        80
112 min        74
Name: count, dtype: int64

In [41]:
# Identify the measurement units used in the duration field
duration_units = (
    netflix_df["duration"]
    .dropna()
    .str.extract(r"([A-Za-z]+(?:\s[A-Za-z]+)?)")[0]
    .value_counts()
)

duration_units

0
min        6126
Season     1791
Seasons     873
Name: count, dtype: int64

In [42]:
# Compare duration formats across movies and TV shows
pd.crosstab(
    netflix_df["type"],
    netflix_df["duration"].str.extract(r"([A-Za-z]+(?:\s[A-Za-z]+)?)")[0],
    dropna=False
)

0        Season  Seasons   min
type
Movie         0        0  6126
TV Show    1791      873     0

#### Duration Consistency Findings
**Finding:** The duration field uses min for movies and Season/Seasons for TV shows. The cross-check with type confirmed that the units are structurally consistent with the content type. Since season counts cannot be reliably converted into viewing minutes without episode-level information, the two measures will be treated separately.

**Action:** No conversion between minutes and seasons will be performed. The duration field will be retained in its original form and may later be separated into a numeric value and measurement unit during feature engineering.

### Checking Title Consistency

The title field is important for identifying and analyzing individual content items. We’ll check for formatting issues such as leading/trailing whitespace, unusual capitalization, and repeated titles. Repeated titles are not automatically errors because different movies or shows can legitimately share the same name.

In [43]:
# Check for leading or trailing whitespace in titles
title_whitespace = netflix_df["title"][
    netflix_df["title"] != netflix_df["title"].str.strip()
]

title_whitespace.unique()

array(['Consequences\xa0'], dtype=object)

In [44]:
# Identify titles that appear more than once
duplicate_titles = netflix_df["title"].value_counts()

duplicate_titles[duplicate_titles > 1].head(20)

title
9-Feb     2
15-Aug    2
22-Jul    2
Name: count, dtype: int64

In [45]:
# Remove leading/trailing whitespace, including non-breaking spaces
netflix_df["title"] = netflix_df["title"].str.replace("\xa0", " ", regex=False).str.strip()

In [46]:
# Confirm that no titles still contain leading or trailing whitespace
title_whitespace = netflix_df["title"][
    netflix_df["title"] != netflix_df["title"].str.strip()
]

title_whitespace.unique()

array([], dtype=object)

In [47]:
# Inspect records with repeated title values
netflix_df[netflix_df["title"].isin(["9-Feb", "15-Aug", "22-Jul"])]

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
393,s3997,TV Show,9-Feb,N/A,Pakistan,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
537,s5965,TV Show,9-Feb,N/A,Pakistan,2019-03-20,2018,TV-14,1 Season,"International TV Shows, TV Dramas"
2925,s3963,Movie,15-Aug,Swapnaneel Jayakar,India,2019-03-29,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"
3285,s4523,Movie,22-Jul,Paul Greengrass,Norway,2018-10-10,2018,R,144 min,"Dramas, Thrillers"
4260,s5966,Movie,22-Jul,Paul Greengrass,Norway,2018-10-10,2018,R,144 min,"Dramas, Thrillers"
4261,s5967,Movie,15-Aug,Swapnaneel Jayakar,India,2019-03-29,2019,TV-14,124 min,"Comedies, Dramas, Independent Movies"

**Finding:** The `title` field contained a non-breaking trailing space in `Consequences`, which was identified as a formatting inconsistency. The field also contained repeated values for `9-Feb`, `15-Aug`, and `22-Jul`. Inspection showed that each repeated value corresponded to identical records, indicating duplicate content records rather than separate titles with the same name.

**Action:** Whitespace formatting was standardized across the `title` field. The repeated records will be investigated further against the raw dataset before any records are removed or titles are modified.

In [48]:
# Identify titles that match common day-month date patterns
date_like_titles = netflix_df[
    netflix_df["title"].str.match(r"^\d{1,2}-[A-Za-z]{3}$", na=False)
]

date_like_titles[["show_id", "title", "type", "date_added"]]

     show_id   title     type date_added
393    s3997   9-Feb  TV Show 2019-03-20
537    s5965   9-Feb  TV Show 2019-03-20
2925   s3963  15-Aug    Movie 2019-03-29
3285   s4523  22-Jul    Movie 2018-10-10
4259   s5964   1-Oct    Movie 2019-09-01
4260   s5966  22-Jul    Movie 2018-10-10
4261   s5967  15-Aug    Movie 2019-03-29

In [49]:
import pandas as pd

# Load the original dataset separately for comparison
netflix_raw = pd.read_csv("Dataset.csv")

In [50]:
netflix_raw.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [51]:
# Compare the suspicious show IDs with their original titles
netflix_raw[
    netflix_raw["show_id"].isin(
        ["s3997", "s5965", "s3963", "s4523", "s5964", "s5966", "s5967"]
    )
][["show_id", "title"]]

     show_id   title
393    s3997   9-Feb
537    s5965   9-Feb
2925   s3963  15-Aug
3285   s4523  22-Jul
4259   s5964   1-Oct
4260   s5966  22-Jul
4261   s5967  15-Aug

In [52]:
# Inspect the complete raw records for the suspicious titles to confirm that we didn't alter the data when loading and preparing it
netflix_raw[
    netflix_raw["show_id"].isin(
        ["s3997", "s5965", "s3963", "s4523", "s5964", "s5966", "s5967"]
    )
].T

,393,537,2925,3285,4259,4260,4261
show_id,s3997,s5965,s3963,s4523,s5964,s5966,s5967
type,TV Show,TV Show,Movie,Movie,Movie,Movie,Movie
title,9-Feb,9-Feb,15-Aug,22-Jul,1-Oct,22-Jul,15-Aug
director,Not Given,Not Given,Swapnaneel Jayakar,Paul Greengrass,Kunle Afolayan,Paul Greengrass,Swapnaneel Jayakar
country,Pakistan,Pakistan,India,Norway,Nigeria,Norway,India
date_added,3/20/2019,3/20/2019,3/29/2019,10/10/2018,9/1/2019,10/10/2018,3/29/2019
release_year,2018,2018,2019,2018,2014,2018,2019
rating,TV-14,TV-14,TV-14,R,TV-14,R,TV-14
duration,1 Season,1 Season,124 min,144 min,149 min,144 min,124 min
listed_in,"International TV Shows, TV Dramas","International TV Shows, TV Dramas","Comedies, Dramas, Independent Movies","Dramas, Thrillers","Dramas, International Movies, Thrillers","Dramas, Thrillers","Comedies, Dramas, Independent Movies"

In [53]:
# Check the original row positions of the suspicious records
netflix_raw[
    netflix_raw["show_id"].isin(
        ["s3997", "s5965", "s3963", "s4523", "s5964", "s5966", "s5967"]
    )
].index

Index([393, 537, 2925, 3285, 4259, 4260, 4261], dtype='int64')

In [55]:
# After confirming that our original dataset had the same errors, we will not continue with our working dataset
# Inspect nearby rows to identify whether the suspicious titles follow a pattern
suspicious_indices = netflix_df[
    netflix_df["show_id"].isin(
        ["s3997", "s5965", "s3963", "s4523", "s5964", "s5966", "s5967"]
    )
].index

netflix_df.loc[
    sorted(set(i for idx in suspicious_indices for i in range(max(0, idx - 2), idx + 3))),
    ["show_id", "title", "type", "date_added"]
]

     show_id                                      title     type date_added
391    s3985                                The 10 Sins  TV Show 2019-03-22
392    s3988  Antoine Griezmann: The Making of a Legend    Movie 2019-03-21
393    s3997                                      9-Feb  TV Show 2019-03-20
394    s4013                                   My Pride  TV Show 2019-03-15
395    s4016      The Disappearance of Madeleine McCann  TV Show 2019-03-15
535     s384                                 Department    Movie 2021-07-27
536     s399                Kingdom: Ashin of the North    Movie 2021-07-23
537    s5965                                      9-Feb  TV Show 2019-03-20
538     s390                              The Operative    Movie 2021-07-27
539    s5975                        แผนร้ายนายเจ้าเล่ห์  TV Show 2019-03-30
2923   s3960                                Mercy Black    Movie 2019-03-31
2924   s3961                         The Burial of Kojo    Movie 2019-03-31
2925   s3963                                     15-Aug    Movie 2019-03-29
2926   s3964                                    Bayonet    Movie 2019-03-29
2927   s3967                             The Highwaymen    Movie 2019-03-29
3283   s4517           ReMastered: Who Shot the Sheriff    Movie 2018-10-12
3284   s4520                   The Kindergarten Teacher    Movie 2018-10-12
3285   s4523                                     22-Jul    Movie 2018-10-10
3286   s4525                      Tales From the Hood 2    Movie 2018-10-10
3287   s4526                      Mo Amer: The Vagabond    Movie 2018-10-09
4257   s5962                                        706    Movie 2019-04-01
4258   s5963                                       1920    Movie 2017-12-15
4259   s5964                                      1-Oct    Movie 2019-09-01
4260   s5966                                     22-Jul    Movie 2018-10-10
4261   s5967                                     15-Aug    Movie 2019-03-29
4262   s5969                               ​Goli Soda 2    Movie 2018-09-15
4263   s5970                         ​Maj Rati ​​Keteki    Movie 2018-09-15

#### Title consistency observation
**Observation:** The title field was generally consistent, with one identified whitespace inconsistency in Consequences, which was standardized. Several titles appeared date-like, but inspection of the raw dataset and surrounding records confirmed that these were valid content titles. Repeated titles were identified separately and will be addressed during duplicate-record cleaning.

### Checking Release Year Validity

The release_year field is numeric, so instead of checking formatting, we want to identify unusual or potentially invalid years. We'll first establish the range before deciding whether anything needs investigation.

In [61]:
# Inspect the distribution and range of release years
netflix_df["release_year"].describe()

count    8790.000000
mean     2014.183163
std         8.825466
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

In [62]:
# Identify the earliest and latest release years
netflix_df["release_year"].agg(["min", "max"])

min    1925
max    2021
Name: release_year, dtype: int64

In [63]:
# Inspect the oldest release years represented in the dataset
netflix_df["release_year"].sort_values().head(20).to_list()

[1925,
 1942,
 1942,
 1943,
 1943,
 1943,
 1944,
 1944,
 1944,
 1945,
 1945,
 1945,
 1945,
 1946,
 1946,
 1947,
 1954,
 1954,
 1955,
 1955]

In [64]:
# Inspect the most recent release years in the dataset
netflix_df["release_year"].sort_values(ascending=False).head(20)

6871    2021
541     2021
531     2021
532     2021
533     2021
534     2021
6877    2021
536     2021
6878    2021
6880    2021
6883    2021
6890    2021
557     2021
6891    2021
6892    2021
6894    2021
6895    2021
6896    2021
6899    2021
6900    2021
Name: release_year, dtype: int64

In [65]:
# Identify records where the release year is later than the year the title was added
year_inconsistencies = netflix_df[
    netflix_df["release_year"] > netflix_df["date_added"].dt.year
]

year_inconsistencies[["title", "release_year", "date_added"]]

                           title  release_year date_added
3869  Hans Teeuwen: Real Rancour          2018 2017-07-01
5138                    Incoming          2019 2018-10-26
5178                 Jack Taylor          2016 2013-03-31
6948                       Hilda          2021 2020-12-14
6992                Polly Pocket          2021 2020-11-15
7355               Love Is Blind          2021 2020-02-13
7436                Fuller House          2020 2019-12-06
7484          Maradona in Mexico          2020 2019-11-13
7517             BoJack Horseman          2020 2019-10-25
7537            The Hook Up Plan          2020 2019-10-11
7996   Unbreakable Kimmy Schmidt          2019 2018-05-30
7997        Arrested Development          2019 2018-05-29
8223                      Sense8          2018 2016-12-23
8235                 Tokyo Trial          2017 2016-12-13

In [67]:
netflix_df["release_year"].unique()

array([2020, 2021, 1993, 2019, 2013, 2014, 2018, 1998, 2010, 2017, 1997,
       1996, 1975, 1978, 1983, 1987, 2012, 2001, 2002, 2003, 2004, 2011,
       2008, 2009, 2007, 2005, 2006, 2016, 1994, 2015, 1982, 1989, 1990,
       1991, 1999, 1986, 1984, 1980, 1961, 2000, 1995, 1985, 1925, 1992,
       1976, 1959, 1988, 1981, 1972, 1964, 1954, 1979, 1958, 1956, 1963,
       1970, 1973, 1960, 1974, 1966, 1971, 1962, 1969, 1977, 1967, 1968,
       1965, 1945, 1946, 1942, 1955, 1944, 1947, 1943], dtype=int64)

**Finding:** The `release_year` field contains values ranging from 1925 to 2021. The values fall within a plausible range for the content represented in the dataset, with no obvious invalid or impossible entries identified.

**Action:** No changes were required for the `release_year` field.

In [73]:
# Check whether content type contains only expected categories
netflix_df["type"].unique()

array(['Movie', 'TV Show'], dtype=object)

### Step 4: Transform categorical and date-related columns.

#### Extracting Date Components

The date_added field has already been converted to datetime format. To make the information easier to analyze and use in downstream models, relevant date components such as year, month, and day will be extracted into separate features.

In [74]:
# Extract useful components from the date the title was added
netflix_df["date_added_year"] = netflix_df["date_added"].dt.year
netflix_df["date_added_month"] = netflix_df["date_added"].dt.month
netflix_df["date_added_day"] = netflix_df["date_added"].dt.day

In [76]:
# Verify the newly created date features
netflix_df[["date_added", "date_added_year", "date_added_month", "date_added_day"]].head(20)

   date_added  date_added_year  date_added_month  date_added_day
0  2021-09-25             2021                 9              25
1  2021-09-24             2021                 9              24
2  2021-09-24             2021                 9              24
3  2021-09-22             2021                 9              22
4  2021-09-24             2021                 9              24
5  2021-09-24             2021                 9              24
6  2021-09-24             2021                 9              24
7  2021-05-01             2021                 5               1
8  2021-09-23             2021                 9              23
9  2021-05-01             2021                 5               1
10 2021-05-01             2021                 5               1
11 2021-05-01             2021                 5               1
12 2021-05-21             2021                 5              21
13 2021-07-13             2021                 7              13
14 2021-06-12             2021                 6              12
15 2021-06-12             2021                 6              12
16 2021-05-07             2021                 5               7
17 2021-09-24             2021                 9              24
18 2021-09-22             2021                 9              22
19 2019-11-26             2019                11              26

#### Feature engineering 
To create new duration columns with values and strings separately 
since we are nit sure of minutes in each season so that we can have all as mins

In [77]:
# Create separate numeric and unit features while preserving the original duration
netflix_df["duration_value"] = netflix_df["duration"].str.extract(r"(\d+)").astype(int)
netflix_df["duration_unit"] = netflix_df["duration"].str.extract(r"([A-Za-z]+)")

In [78]:
# Standardize singular and plural season labels
netflix_df["duration_unit"] = netflix_df["duration_unit"].replace({
    "Seasons": "Season"
})

In [79]:
# Check the transformed duration features
netflix_df[["type", "duration", "duration_value", "duration_unit"]].head(10)

      type   duration  duration_value duration_unit
0    Movie     90 min              90           min
1  TV Show   1 Season               1        Season
2  TV Show   1 Season               1        Season
3    Movie     91 min              91           min
4    Movie    125 min             125           min
5  TV Show  9 Seasons               9        Season
6    Movie    104 min             104           min
7    Movie     87 min              87           min
8    Movie    127 min             127           min
9    Movie     76 min              76           min

In [80]:
# Confirm the duration units and their distribution
netflix_df["duration_unit"].value_counts()

duration_unit
min       6126
Season    2664
Name: count, dtype: int64

### Transforming Content Categories

The `listed_in` field contains one or more content categories separated by commas. The individual categories will be extracted so they can be analyzed as separate categorical features while preserving the original field.

In [81]:
# Split the listed categories into individual values
genre_lists = netflix_df["listed_in"].str.split(", ")

# Inspect a few examples
genre_lists.head()

0                                      [Documentaries]
1    [Crime TV Shows, International TV Shows, TV Ac...
2                 [TV Dramas, TV Horror, TV Mysteries]
3                 [Children & Family Movies, Comedies]
4    [Dramas, Independent Movies, International Mov...
Name: listed_in, dtype: object

In [82]:
# Count the number of categories assigned to each title
netflix_df["genre_count"] = genre_lists.str.len()

In [83]:
# Check the distribution of categories assigned to each title
netflix_df["genre_count"].value_counts().sort_index()

genre_count
1    2012
2    3052
3    3726
Name: count, dtype: int64

#### Validating Transformed Features

The newly created features will be checked to confirm that the transformations were applied correctly and did not introduce unexpected missing values or inconsistencies.

In [88]:
# Review the structure and data types after feature transformation 
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   show_id           8790 non-null   object
 1   type              8790 non-null   object
 2   title             8790 non-null   object
 3   director          8790 non-null   object
 4   country           8790 non-null   object
 5   date_added        8790 non-null   datetime64[ns]
 6   release_year      8790 non-null   int64
 7   rating            8790 non-null   object
 8   duration          8790 non-null   object
 9   listed_in         8790 non-null   object
 10  date_added_year   8790 non-null   int32
 11  date_added_month  8790 non-null   int32
 12  date_added_day    8790 non-null   int32
 13  duration_value    8790 non-null   int32
 14  duration_unit     8790 non-null   object
 15  genre_count       8790 non-null   int64
dtypes: datetime64[ns](1), int32(4), int64(2), object(9)
memory usage: 961.5+ KB

In [89]:
# Check for missing values in the newly created features 
netflix_df[ ["date_added_year", "date_added_month", 
             "date_added_day", "duration_value", 
             "duration_unit", "genre_count"] ].isna().sum()

date_added_year     0
date_added_month    0
date_added_day      0
duration_value      0
duration_unit       0
genre_count         0
dtype: int64

In [91]:
# Confirm that the final dataset contains no exact duplicate records
netflix_df.duplicated().sum()

0

In [90]:
# Preview the transformed dataset
netflix_df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,date_added_year,date_added_month,date_added_day,duration_value,duration_unit,genre_count
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,2021,9,25,90,min,1
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2021,9,24,1,Season,3
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",2021,9,24,1,Season,3
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",2021,9,22,91,min,2
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",2021,9,24,125,min,3

### Step 5: Create a clean dataset for further analysis

In [92]:
# Save the cleaned and transformed dataset for use in downstream notebooks
netflix_df.to_csv("netflix_cleaned.csv", index=False)

## Data Wrangling and Dataset Preparation

The raw Netflix dataset was systematically assessed and prepared for downstream analysis and modeling. The process included data inspection, quality assessment, consistency checks, cleaning, transformation, and feature engineering.

#### Key preparation steps included:

1. Standardizing inconsistent text values and whitespace.
2. Validating categorical fields and checking for duplicate records.
3. Assessing missing values and handling source-level missing information codes.
4. Validating date and release-year fields for appropriate formats and plausible values.
5. Converting date_added to a datetime format and extracting year, month, and day features.
6. Separating duration into numeric values and measurement units while preserving the original field.
7. Extracting the number of categories associated with each title through the genre_count feature.
8. Preserving multi-value fields such as country and listed_in for use in downstream analysis.
9. Performing final validation to ensure the processed dataset is structurally consistent and ready for further analysis.

The resulting clean dataset provides a reliable foundation for exploratory analysis, recommendation modeling, trend forecasting, and classification tasks in the subsequent project stages.